version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://database:3306/AppTaxiDay
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      database:
        condition: service_healthy
    networks:
      - taxi-net
    restart: unless-stopped

  web-frontend:
    build:
      context: ./WebFrontend
      dockerfile: Dockerfile
    container_name: react-web-app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    networks:
      - taxi-net
    restart: unless-stopped

  mobile-frontend:
    build:
      context: ./MobileFrontend
      dockerfile: Dockerfile
    container_name: react-native-app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    networks:
      - taxi-net
    restart: unless-stopped

  database:
    image: mariadb:11.2
    container_name: taxiday_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AppTaxiDay
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - taxi-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  taxi-net:
    driver: bridge

volumes:
  db_data: