version: "3.8"

services:
  database:
    image: mariadb:10.7
    container_name: taxiday_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AppTaxiDay
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"

  backend:
    build:
      context: ./Backend
    container_name: spring-boot-app
    depends_on:
      - database
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/AppTaxiDay
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  webfrontend:
    build:
      context: ./Frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
